# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HowlFireBaseLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HowlFireBaseLogin








pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Crash'
pod 'Fabric', '~> 1.7.2'
pod 'Crashlytics', '~> 3.9.3'


pod 'GoogleSignIn'


pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'









end
