# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HowlTalk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HowlTalk






pod 'SnapKit', '~> 4.0.0'

pod 'Firebase/Core'
pod 'Firebase/RemoteConfig'
pod 'TextFieldEffects'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'

pod 'Alamofire', '~> 4.7'
pod 'Kingfisher', '~> 4.7'
pod 'MaterialComponents/Buttons+Extensions'
pod 'ObjectMapper', '~>3.1'
 
pod 'BEMCheckBox'




end
